add homework #3
DaniilKorinnyi/study pull request #1
Opened 2022-12-11 15:07 UTC by DaniilKorinnyi

Homework #3

2022-12-12 20:02 UTC, klymenok requested changes
Please, make changes according to comments

2022-12-12 20:02 UTC, klymenok commented on homework3/task2.py
> +your_age =input("Write your age: ")
You shouldn't use input() here. Just create a variable with a value directly

2022-12-12 20:02 UTC, klymenok commented on homework3/task3.py
> +my_name = input("Your name: ")
You shouldn't use input() here. Just create a variable with a value directly

2022-12-12 20:02 UTC, klymenok commented on homework3/task3.py
> +age_in_years = input("Your age: ")
You shouldn't use input() here. Just create a variable with a value directly

2022-12-13 12:59 UTC, DaniilKorinnyi reviewed
Some changes in task 2 and 3

2022-12-13 17:48 UTC, klymenok approved these changes
Looks good

2022-12-15 09:59 UTC, merged