Homework18
DaniilKorinnyi/study pull request #17
Opened 2023-04-03 17:10 UTC by DaniilKorinnyi

Added flask_homework2

2023-04-06 18:33 UTC, klymenok approved these changes
Looks good!

2023-04-09 22:08 UTC, klymenok requested changes
Завдання 3 не виконане

2023-04-10 06:35 UTC, DaniilKorinnyi commented
I apologize for my inattention

2023-04-11 20:38 UTC, klymenok approved these changes
Looks good!

2023-04-12 13:52 UTC, merged