Some files have been added
DaniilKorinnyi/study pull request #18
Opened 2023-04-12 20:41 UTC by DaniilKorinnyi

2023-04-17 20:25 UTC, klymenok requested changes

2023-04-17 20:25 UTC, klymenok commented on homework18/instance/flask-database.sqlite
Базу даних можна також додати в gitignore. Такого типу файли зазвичай не пушаться на git бо не мають цінності з точки зору контролю версій

2023-04-17 20:25 UTC, klymenok commented on homework18/flask_app/models.py
> +    def __iter__(self):
А для чого ви тут перевизначаєте __iter__?

2023-04-19 20:54 UTC, DaniilKorinnyi commented on homework18/flask_app/models.py
> +    def __iter__(self):
Тому що, при запуску ендпоїнта(@app.route('/users/<int:id>')) видає помилку: TypeError: argument of type 'Purchase' is not iterable

2023-04-19 20:56 UTC, DaniilKorinnyi commented on homework18/flask_app/models.py
> +    def __iter__(self):
Завчасно вибачаюся за неправильну назву коміту

2023-04-21 15:55 UTC, klymenok commented on homework18/flask_app/models.py
> +    def __iter__(self):
Python вам правильно підказує -  ви намагаєтеся здійснити дію, яка не притаманна обʼєктам що не можуть бути ітерованими. Заміть того, щоб виправляти це на рівні обʼєкта, можна виправити це на рівні правильного поводження із ним.
Ось це місце спричиняє помилку
```
{% if id in users %}
```
А замість частини в блоці else, ви можете у view функції перевірити чи знайдений такий обʼєкт в базі даних і  повернути помилку 404 якщо ні.
```
user = User.query.get(id)
if not user:
    return 404
current = session.get('user')
if current:
    return render_template('usersid.html', users=users, id=id)
else:
    return redirect(url_for('login'))
```

Так само і в інших подібних функціях

2023-04-22 07:10 UTC, DaniilKorinnyi commented on homework18/flask_app/models.py
> +    def __iter__(self):
Зрозумів, дякую. Зараз буду виправляти.

2023-04-23 11:10 UTC, klymenok approved these changes
Looks good!

2023-04-26 08:12 UTC, merged