add homework6
DaniilKorinnyi/study pull request #4
Opened 2022-12-20 14:07 UTC by DaniilKorinnyi

Added homework6

2022-12-22 18:33 UTC, klymenok requested changes

2022-12-22 18:33 UTC, klymenok commented on homework6/task.py
> +stats = len(phone_book)
this variable should be updated every time when structure of the phonebook is changed. It is better to put it after 'stat' command or use `len(phone_book)` there

2022-12-22 18:33 UTC, klymenok commented on homework6/task.py
> +        del phone_book[name]
It is better to check if key exists before deleting it

2022-12-22 18:33 UTC, klymenok commented on homework6/task.py
> +        phone_book[name] = c
Records shouldn't be overridden according to the task. Please, make additional check here

2022-12-26 14:14 UTC, DaniilKorinnyi reviewed
Some correction in homework6

2022-12-26 21:00 UTC, klymenok approved these changes
Looks good!

2022-12-27 13:33 UTC, DaniilKorinnyi commented
> Looks good!

Thanks!

2022-12-27 13:33 UTC, merged