Added homework11
DaniilKorinnyi/study pull request #9
Opened 2023-02-08 19:19 UTC by DaniilKorinnyi

Homework11 was added

2023-02-09 21:48 UTC, klymenok requested changes

2023-02-09 21:48 UTC, klymenok commented on homework11/task2.py
> +# class User:
remove commented code or uncomment it to be evaluated

2023-02-09 21:48 UTC, klymenok commented on homework11/task2.py
> +MyStr("hello")
Your class does't work like this:
```
my_str = MyStr('test')
print(my_str)
>>> "TEST"
```

To make it works you should override `__str__` method - print uses this method to get a string representation for objects.

2023-02-09 21:48 UTC, klymenok commented on homework11/task2.py
> +#         return self.name.lower() == other
Almost. Add `other.name.lower()` and it should work

2023-02-13 17:57 UTC, DaniilKorinnyi reviewed
Changed homework12

2023-02-18 08:23 UTC, DaniilKorinnyi commented
> Looks good, but I guess homework 12 shouldn't be here

Yes, I didn't see that I'd committed to this branch. I reverted the commit, but nothing changed. Maybe the reason  is that I had already sent for reviewing. Or something else, don't you know?

2023-02-18 08:38 UTC, merged